### ISSUE TITLE
Google pay shows processing forever if google pay button is embedded in iframe and webpage is viewed on mobile

### ISSUE THREAD

**Issue by jacob-pecile-CH** [google-pay/google-pay-button#140] opened 2022-06-24 17:00 UTC
**Describe the bug** A clear and concise description of what the bug is.
I have the google pay button working on a form, but if that form is embedded on another page and that page is being viewed on a mobile device the google window never loads credit cards and instead shows a loading spinner and says processing forever

**To Reproduce** Steps to reproduce the behavior:

1. Load google pay react button within an iframe on mobile device
2. Click on google pay button
3. google pay window hangs on "processing" view

**Expected behavior** A clear and concise description of what you expected to happen.
google window finishes processing and shows credit cards

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/96441365/175607414-6ce11731-c667-426b-addc-ea850d80fe4b.png)

**Component information:**

- Component
  - [X] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [ ] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

only appears to occur on chrome from a mobile view (whether an actual phone or using the mobile view from dev tools)
Google button must be embedded within an iframe.
Was using the react google pay button in the TEST environment

**Comment by dmengelt** [comment] 2023-02-03 13:38
@jacob-pecile-CH do you still experience this issue? If yes, could you maybe send a link where I can reproduce the issue?

**Comment by dmengelt** [comment] 2023-04-21 11:21
Closing due to inacticity.

**Closed by dmengelt** 2023-04-21 11:21 UTC
Labels: bug
