### ISSUE TITLE
Google pay has style issue when adding cvcRequired: true

### ISSUE THREAD

**Issue by shirly-chen-awx** [google-pay/google-pay-button#206] opened 2023-02-14 10:04 UTC
**Describe the bug** After adding cvcRequired true into paymentRequest and buttonSizeMode is fill, it only shows "Buy with google pay" and text is not centered. see the demo in jsfiddle -> https://jsfiddle.net/txq0zpf8/14/

**Expected behavior**  The button should be able to see the last four of the card number and the text is centered.
see the demo implemented by js -> https://jsfiddle.net/Lrktw9x0/2/
<img width="526" alt="image" src="https://user-images.githubusercontent.com/68316896/218702424-4f380a1e-4ad3-41b6-a32e-9bed8379979f.png">

**Screenshots** 
chrome:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/68316896/218702140-fece03a2-85be-4ba3-8f34-08aa88dada0d.png">
safari:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/68316896/218702966-b561dcb4-b508-4742-aa57-9579ed885d15.png">

**Component information:**

- Component
  - [x] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [ ] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**
- Browser: all browsers
- Country/region: all regions

**Comment by dmengelt** [comment] 2023-02-14 11:30
Thanks for reporting this @shirly-chen-awx 
At the moment `cvvRequired` is not supported for our button components. You can find all the supported properties here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/googlepay/index.d.ts#L735

**Comment by shirly-chen-awx** [comment] 2023-02-15 02:23
Hi, @dmengelt , are we going to support that? 
The cvcRequired function is working as expect(see the below picture), the react google button only have the style issue. 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/68316896/218910912-e9f750bf-cd9d-4bd6-a250-4e5171df8f94.png">

Here is the background: we have contacted google as this this [article](https://developers.google.com/pay/api/processors/support/troubleshooting?hl=en#cvc-card-required) said. We got the reply that we need to add cvcRequired into the paymentRequest and the cvcRequired field is not publicly documented on the dev site.

**Comment by dmengelt** [comment] 2023-02-17 08:29
@shirly-chen-awx we are looking into it. I hope I have an update soon.

**Comment by dmengelt** [comment] 2023-02-28 10:33
Seems like updating to @types/googlepay 0.7.0 (and therefore supporting `cvcRequired`) was not enough. Will investigate further...

**Comment by dmengelt** [comment] 2023-02-28 15:05
Ok we finally found the issue. Will report back as soon as we have an update... Sorry for the inconvenience!

**Comment by shirly-chen-awx** [comment] 2023-03-10 03:24
hey, @dmengelt, do we have any updates about this?

**Comment by dmengelt** [comment] 2023-03-10 09:22
Hey @shirly-chen-awx
We are still working on it.

**Comment by shirly-chen-awx** [comment] 2023-03-28 02:29
@dmengelt Thanks for the timely update

**Comment by dmengelt** [comment] 2023-04-04 08:24
@shirly-chen-awx we just deployed a fix for this. Production deployment should still happen this week. Will keep you posted.

**Comment by dmengelt** [comment] 2023-04-11 08:16
@shirly-chen-awx we rolled out a fix. The issue is now fixed.

**Closed by dmengelt** 2023-04-11 08:16 UTC
Labels: bug

**Comment by shirly-chen-awx** [comment] 2023-04-11 11:49
@dmengelt Thanks a lot!!!
