### ISSUE TITLE
Button not appearing in Firefox and Safari

### ISSUE THREAD

**Issue by wislert** [google-pay/google-pay-button#199] opened 2023-01-11 14:15 UTC
**Describe the bug**: Button not appearing in Firefox/Safari

**To Reproduce**: Open the page with GPay Button

**Expected behavior**: Button works in all browsers

**Screenshots** 
Firefox:
<img width="500" alt="firefox" src="https://user-images.githubusercontent.com/7439798/211825998-661e0d12-e089-460e-aa55-38e928a9d971.png">

Safari:
<img width="500" alt="safari" src="https://user-images.githubusercontent.com/7439798/211826414-3ad9012c-1689-4dd3-bf44-070555e4325d.png">

Chrome:
<img width="500" alt="chrome" src="https://user-images.githubusercontent.com/7439798/211827089-c9985ea8-fe11-4b59-ae4f-96a9301eed0a.png">

**Component information:**

- Component
  - React component (`@google-pay/button-react`)
- Component version: 3.0.5 

**Environment:**

- Device: Macbook Air M1
- OS: MacOS 13.0.1 (22A400)
- Browsers:
  - Firefox 108.0.2 x64
  - Safari 16.1 (18614.2.9.1.12)

**Comment by dmengelt** [comment] 2023-01-11 15:19
@wislert thanks for reporting this. are you able to reproduce the issue here: https://stackblitz.com/edit/google-pay-react-ecbhkg?file=src%2FApp.js

thanks for a quick feedback

**Comment by wislert** [comment] 2023-01-12 08:20
When I removed the property **existingPaymentMethodRequired** this problem was gone.

**Comment by dmengelt** [comment] 2023-01-12 09:55
Thanks for reporting back. If you specify `existingPaymentMethodRequired=true` the `result` property of the [`IsReadyToPayResponse`](https://developers.google.com/pay/api/web/reference/response-objects#IsReadyToPayResponse) only returns true in the following scenario:

> The current visitor is able to provide payment information to the site that requests it. A visitor's ability to pay may be tied to their web browser's ability to display required components for the specified payment methods. This includes when they log in to a Google Account and provide a payment method.

This only affects the `PRODUCTION` environment.

See the details here: https://github.com/google-pay/google-pay-button/blob/main/src/lib/button-manager.ts#L260

**Comment by dmengelt** [comment] 2023-01-12 15:07
@wislert Does it work as expected for you now? If not, is there a way for me to reach your site? If this is not possible please share your full Google Pay Button config here. (specifically `existingPaymentMethodRequired` and `allowedPaymentMethods`)

**Comment by dmengelt** [comment] 2023-02-03 13:28
Closing due to no feedback

**Closed by dmengelt** 2023-02-03 13:28 UTC
Labels: bug
